vals:
  first_access:
    db: YOUR_DATABASE
    tbl: YOUR_TABLE
    output_db: PUTPUT_DATABASE
    output_tbl: ms_behavior_first_access
    fixed_cols:
      - td_cookie
      - media_name
    processing:
      - MIN(time) AS time
      - MIN(access_date_time) AS access_date_time
      #- MIN_BY(td_source_medium,time) AS td_source_medium
    td_url:
      CONCAT('初回アクセス | ',access_date_time)
    where_bulk:
    where_regular:
      - TD_INTERVAL(time,'-1d','JST')
      