media:
  sample_1:
    media_name: sample_1
    # Pageviwe設定
    log_db: YOUR_WEB_LOG_DB #set web_log database
    log_tbl: YOUR_WEB_LOG_TB #set web_log table
    primary_cookie: td_ssc_id #td_ssc_id or td_client_id
    sub_cookie: td_client_id
    td_ssc_id: td_ssc_id #td_ssc_id未取得の場合 CAST(IF(1=1,NULL,NULL) AS STRING)
    user_id: user_id #set user_id column未取得の場合 CAST(IF(1=1,NULL,NULL) AS STRING)
    pv_columns:
      columns:
        #- text #追加カラムがない場合未記載(計算クエリ可:Hive)
    # Click設定
    check_click: false
    click_db: YOUR_CLICK_LOG_DB
    click_tbl: YOUR_CLICK_LOG_TB
    click_col: click_url
    primary_cookie_click: td_ssc_id #td_ssc_id or td_client_id
    sub_cookie_click: td_client_id
    td_ssc_id_click: td_ssc_id #td_ssc_id未取得の場合 CAST(IF(1=1,NULL,NULL) AS STRING)
    user_id_click: CAST(IF(1=1,NULL,NULL) AS STRING) #set user_id column未取得の場合 CAST(IF(1=1,NULL,NULL) AS STRING)
    click_columns:
      columns:
        #- text #追加カラムがない場合未記載(計算クエリ可)
    # 読了設定
    check_read: false
    read_db: YOUR_READ_LOG_DB
    read_tbl: YOUR_READ_LOG_TB
    read_col: scroll_depth_threshold
    primary_cookie_read: td_ssc_id #td_ssc_id or td_client_id
    sub_cookie_read: td_client_id
    td_ssc_id_read: td_ssc_id #td_ssc_id未取得の場合 CAST(IF(1=1,NULL,NULL) AS STRING)
    user_id_read: CAST(IF(1=1,NULL,NULL) AS STRING) #set user_id column未取得の場合 CAST(IF(1=1,NULL,NULL) AS STRING)
    read_columns:
      columns:
        #- text #追加カラムがない場合未記載(計算クエリ可)
    # 設定したすべてのカスタムカラム設定
    all_columns:
      columns:
        #- click_url # クリック集計している場合
        #- read # 読了集計している場合
        #- text #追加カラムがない場合未記載
