media:
  sample_1:
    media_name: sample_1
    # Pageviwe設定
    log_db: YOUR_WEB_LOG_DB #set web_log database
    log_tbl: YOUR_WEB_LOG_TB #set web_log table
    primary_cookie: td_ssc_id #td_ssc_id or td_client_id
    sub_cookie: td_client_id
    td_ssc_id: td_ssc_id #td_ssc_id未取得の場合 "''"
    user_id: user_id #set user_id column未取得の場合 "''"
    pv_columns:
      columns:
        #- text #追加カラムがない場合未記載(計算クエリ可)
    pv_first_regular_other_process: # Hive/Prestoで異なるカラム展開処理がある場合
      first: 
        #- IF(a RLILE 'aa',1,0) AS col1
      regular:
        #- IF(regexp_like(a,'aa'),1,0) AS col1
    # Click設定
    check_click: true
    click_db: YOUR_CLICK_LOG_DB
    click_tbl: YOUR_CLICK_LOG_TB
    click_col: click_url
    primary_cookie_click: td_ssc_id #td_ssc_id or td_client_id
    sub_cookie_click: td_client_id
    td_ssc_id_click: td_ssc_id #td_ssc_id未取得の場合 "''"
    user_id_click: "''" #set user_id column未取得の場合 "''"
    click_columns:
      columns:
        #- text #追加カラムがない場合未記載(計算クエリ可)
    click_first_regular_other_process:
      first: 
      regular:
    # 読了設定
    check_read: true
    read_db: YOUR_READ_LOG_DB
    read_tbl: YOUR_READ_LOG_TB
    read_col: scroll_depth_threshold
    primary_cookie_read: td_ssc_id #td_ssc_id or td_client_id
    sub_cookie_read: td_client_id
    td_ssc_id_read: td_ssc_id #td_ssc_id未取得の場合 "''"
    user_id_read: "''" #set user_id column未取得の場合 "''"
    read_columns:
      columns:
        #- text #追加カラムがない場合未記載(計算クエリ可)
    read_first_regular_other_process:
      first: 
      regular:
    # 設定したすべてのカスタムカラム設定
    all_columns:
      columns:
        #- click_url # クリック集計している場合
        #- read # 読了集計している場合
        #- text #追加カラムがない場合未記載
    # 最終処理でもう一度展開処理が発生する場合
    all_first_regular_other_process:
      first: 
      regular:
