td:
  database: td_sandbox

roi_judge_date: 7

# Webログ設定
web:
  db: WEB_LOG_DB
  tbl: WEB_LOG_TBL
  time_col: time
  user_id: user_id_comp
  utm_source: td_source
  utm_medium: td_medium
  utm_campaign: utm_campaign
  where_condition:
    #- session_num = 1

# 購買ログ設定
pos:
  db: POS_LOG_DB
  tbl: POS_LOG_TBL
  time_col: TD_TIME_PARSE(TD_TIME_FORMAT(time, 'yyyy-MM-dd 23:59:59','JST'),'JST') #購入日がyyyy-MM-ddで入っている場合は、23:59:59を追加した方が良い
  user_id: user_id
  amount_col: AMOUNT_COL
  add_cols:
    #- カラムが追加になる場合以下に追記
    #- order_id
    #- brand
    #- itemcd
    #- product_id
    #- product_name 
  where_condition:
   # - product_name not RLIKE '無料'

# 結果出力設定
resurl_add_col:
  - brand
result_type: googlesheet
result_google:
  result_1:
    connecter: GOOGLESHEET_CONNECTER_NAME
    folder: GOOGLESHEET_FOLDER_ID
